"""initial_commit

Revision ID: 738f3a0ae70f
Revises: 
Create Date: 2024-06-27 13:43:11.057050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738f3a0ae70f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hy_c_dCity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('City', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dFirstProperty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('FirstProperty', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dGender',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Gender', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dInactiveStates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('InactiveState', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dMaritalStatus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('MaritalStatus', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dNeighborhood',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Neighborhood', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dObjectives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Objective', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dState',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('State', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dStatus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Status', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dUsers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('CPF', sa.String(length=255), nullable=True),
    sa.Column('Regional', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_ch_dRating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('Rating', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_ch_dUsers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dChannels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Channel', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dMediaGroups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('MediaGroup', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dMedias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Media', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dMoments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Moment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dProducts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Product', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dSubChannels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('SubChannel', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dSubMoments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('SubMoment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dTemperatures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Temperature', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_msg_dStatus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MessageStatus', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_msg_dType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MessageType', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_msg_dUsers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idHyCRM', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_products',
    sa.Column('CodProduto', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('CodInterno', sa.String(length=50), nullable=True),
    sa.Column('DataAtualizacao', sa.DateTime(), nullable=True),
    sa.Column('CodRegional', sa.Integer(), nullable=True),
    sa.Column('Produto', sa.String(length=255), nullable=False),
    sa.Column('Regional', sa.String(length=50), nullable=True),
    sa.Column('Finalidade', sa.String(length=50), nullable=True),
    sa.Column('IdTipoProduto', sa.Integer(), nullable=True),
    sa.Column('TipoProduto', sa.String(length=50), nullable=True),
    sa.Column('FaseProduto', sa.String(length=50), nullable=True),
    sa.Column('Descricao', sa.Text(), nullable=True),
    sa.Column('AnoEntrega', sa.Integer(), nullable=True),
    sa.Column('ValorDe', sa.Float(), nullable=True),
    sa.Column('ValorAte', sa.Float(), nullable=True),
    sa.Column('AreaUtilDe', sa.Float(), nullable=True),
    sa.Column('AreaUtilAte', sa.Float(), nullable=True),
    sa.Column('DormitoriosDe', sa.Integer(), nullable=True),
    sa.Column('DormitoriosAte', sa.Integer(), nullable=True),
    sa.Column('SuitesDe', sa.Integer(), nullable=True),
    sa.Column('SuitesAte', sa.Integer(), nullable=True),
    sa.Column('BanheiroDe', sa.Integer(), nullable=True),
    sa.Column('BanheiroAte', sa.Integer(), nullable=True),
    sa.Column('VagasDe', sa.Integer(), nullable=True),
    sa.Column('VagasAte', sa.Integer(), nullable=True),
    sa.Column('Caracteristicas', sa.Text(), nullable=True),
    sa.Column('UrlChat', sa.String(length=255), nullable=True),
    sa.Column('TotalBanheiroDe', sa.Integer(), nullable=True),
    sa.Column('TotalBanheiroAte', sa.Integer(), nullable=True),
    sa.Column('TotalVagaDe', sa.Integer(), nullable=True),
    sa.Column('TotalVagaAte', sa.Integer(), nullable=True),
    sa.Column('TotalDormitorioDe', sa.Integer(), nullable=True),
    sa.Column('TotalDormitorioAte', sa.Integer(), nullable=True),
    sa.Column('TotalAreaUtilDe', sa.Float(), nullable=True),
    sa.Column('TotalAreaUtilAte', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('CodProduto')
    )
    op.create_table('hy_users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Creci', sa.String(length=255), nullable=True),
    sa.Column('CreciType', sa.String(length=255), nullable=True),
    sa.Column('CreciValidity', sa.String(length=255), nullable=True),
    sa.Column('CPF', sa.String(length=255), nullable=True),
    sa.Column('IdProfile', sa.Integer(), nullable=True),
    sa.Column('IdManager', sa.Integer(), nullable=True),
    sa.Column('IdManager1', sa.Integer(), nullable=True),
    sa.Column('IdManager2', sa.Integer(), nullable=True),
    sa.Column('IdManager3', sa.Integer(), nullable=True),
    sa.Column('IdManager4', sa.Integer(), nullable=True),
    sa.Column('IdManager5', sa.Integer(), nullable=True),
    sa.Column('IdManager6', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('NickName', sa.String(length=255), nullable=True),
    sa.Column('Phone', sa.String(length=255), nullable=True),
    sa.Column('Photo', sa.String(length=255), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.Column('LegacyUserId', sa.Integer(), nullable=True),
    sa.Column('DescriptionStatus', sa.String(length=255), nullable=True),
    sa.Column('DateRegister', sa.DateTime(), nullable=True),
    sa.Column('DateUpdate', sa.DateTime(), nullable=True),
    sa.Column('DateBirth', sa.DateTime(), nullable=True),
    sa.Column('DateAdmission', sa.DateTime(), nullable=True),
    sa.Column('DateLastEvaluation', sa.DateTime(), nullable=True),
    sa.Column('Gender', sa.String(length=255), nullable=True),
    sa.Column('AverageRating', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('num_records', sa.Integer(), nullable=True),
    sa.Column('unique_emails', sa.Integer(), nullable=True),
    sa.Column('unique_phones', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('param_data_inicio', sa.String(length=50), nullable=True),
    sa.Column('param_data_atualizacao_inicio', sa.String(length=50), nullable=True),
    sa.Column('param_data_atualizacao_final', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_fClients',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('InternalCode', sa.String(length=255), nullable=True),
    sa.Column('DateRegister', sa.DateTime(), nullable=True),
    sa.Column('DateLastInteraction', sa.DateTime(), nullable=True),
    sa.Column('Denylist', sa.Boolean(), nullable=True),
    sa.Column('Consent', sa.Boolean(), nullable=True),
    sa.Column('IdObjective', sa.Integer(), nullable=True),
    sa.Column('IdMoment', sa.Integer(), nullable=True),
    sa.Column('IdSubMoment', sa.Integer(), nullable=True),
    sa.Column('IdTemperature', sa.Integer(), nullable=True),
    sa.Column('IdStatus', sa.Integer(), nullable=True),
    sa.Column('IdInactiveState', sa.Integer(), nullable=True),
    sa.Column('IdProductOrigin', sa.Integer(), nullable=True),
    sa.Column('IdProductInterest', sa.Integer(), nullable=True),
    sa.Column('IdFirstProperty', sa.Integer(), nullable=True),
    sa.Column('IdSourceChannel', sa.Integer(), nullable=True),
    sa.Column('IdSourceMedia', sa.Integer(), nullable=True),
    sa.Column('IdCurrentMedia', sa.Integer(), nullable=True),
    sa.Column('IdMediaOriginGroup', sa.Integer(), nullable=True),
    sa.Column('IdCurrentMediaGroup', sa.Integer(), nullable=True),
    sa.Column('IdBroker', sa.Integer(), nullable=True),
    sa.Column('IdBrokerOrigin', sa.Integer(), nullable=True),
    sa.Column('IdManager', sa.Integer(), nullable=True),
    sa.Column('IdGeneralManager', sa.Integer(), nullable=True),
    sa.Column('EmailManagerOrigin', sa.Integer(), nullable=True),
    sa.Column('IdBrokerShared', sa.Integer(), nullable=True),
    sa.Column('IdCoordinator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EmailManagerOrigin'], ['hy_c_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdBroker'], ['hy_c_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdBrokerOrigin'], ['hy_c_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdBrokerShared'], ['hy_c_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdCoordinator'], ['hy_c_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdCurrentMedia'], ['hy_dMedias.id'], ),
    sa.ForeignKeyConstraint(['IdCurrentMediaGroup'], ['hy_dMediaGroups.id'], ),
    sa.ForeignKeyConstraint(['IdFirstProperty'], ['hy_c_dFirstProperty.id'], ),
    sa.ForeignKeyConstraint(['IdGeneralManager'], ['hy_c_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdInactiveState'], ['hy_c_dInactiveStates.id'], ),
    sa.ForeignKeyConstraint(['IdManager'], ['hy_c_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdMediaOriginGroup'], ['hy_dMediaGroups.id'], ),
    sa.ForeignKeyConstraint(['IdMoment'], ['hy_dMoments.id'], ),
    sa.ForeignKeyConstraint(['IdObjective'], ['hy_c_dObjectives.id'], ),
    sa.ForeignKeyConstraint(['IdProductInterest'], ['hy_dProducts.id'], ),
    sa.ForeignKeyConstraint(['IdProductOrigin'], ['hy_dProducts.id'], ),
    sa.ForeignKeyConstraint(['IdSourceChannel'], ['hy_dChannels.id'], ),
    sa.ForeignKeyConstraint(['IdSourceMedia'], ['hy_dMedias.id'], ),
    sa.ForeignKeyConstraint(['IdStatus'], ['hy_c_dStatus.id'], ),
    sa.ForeignKeyConstraint(['IdSubMoment'], ['hy_dSubMoments.id'], ),
    sa.ForeignKeyConstraint(['IdTemperature'], ['hy_dTemperatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_ch_fChat',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ClientName', sa.String(length=255), nullable=True),
    sa.Column('ClientEmail', sa.String(length=255), nullable=True),
    sa.Column('ClientPhone', sa.String(length=255), nullable=True),
    sa.Column('ClientIP', sa.String(length=50), nullable=True),
    sa.Column('ChatType', sa.Integer(), nullable=False),
    sa.Column('ActiveClient', sa.Boolean(), nullable=True),
    sa.Column('NewClient', sa.Boolean(), nullable=True),
    sa.Column('StartTimeDate', sa.DateTime(), nullable=True),
    sa.Column('EndTimeDate', sa.DateTime(), nullable=True),
    sa.Column('RatingComment', sa.Text(), nullable=True),
    sa.Column('IdBroker_responsible', sa.Integer(), nullable=True),
    sa.Column('IdBroker_attendant', sa.Integer(), nullable=True),
    sa.Column('IdBroker_forwarded', sa.Integer(), nullable=True),
    sa.Column('IdManager_responsible', sa.Integer(), nullable=True),
    sa.Column('IdClient', sa.Integer(), nullable=True),
    sa.Column('IdRating', sa.Integer(), nullable=True),
    sa.Column('IdProduct', sa.Integer(), nullable=True),
    sa.Column('IdChannel', sa.Integer(), nullable=True),
    sa.Column('IdSubChannel', sa.Integer(), nullable=True),
    sa.Column('IdMoment', sa.Integer(), nullable=True),
    sa.Column('IdSubMoment', sa.Integer(), nullable=True),
    sa.Column('IdMedium', sa.Integer(), nullable=True),
    sa.Column('IdMediumGroup', sa.Integer(), nullable=True),
    sa.Column('Idtemperature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IdBroker_attendant'], ['hy_ch_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdBroker_forwarded'], ['hy_ch_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdBroker_responsible'], ['hy_ch_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdChannel'], ['hy_dChannels.id'], ),
    sa.ForeignKeyConstraint(['IdManager_responsible'], ['hy_ch_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdMedium'], ['hy_dMedias.id'], ),
    sa.ForeignKeyConstraint(['IdMediumGroup'], ['hy_dMediaGroups.id'], ),
    sa.ForeignKeyConstraint(['IdMoment'], ['hy_dMoments.id'], ),
    sa.ForeignKeyConstraint(['IdProduct'], ['hy_dProducts.id'], ),
    sa.ForeignKeyConstraint(['IdRating'], ['hy_ch_dRating.id'], ),
    sa.ForeignKeyConstraint(['IdSubChannel'], ['hy_dSubChannels.id'], ),
    sa.ForeignKeyConstraint(['IdSubMoment'], ['hy_dSubMoments.id'], ),
    sa.ForeignKeyConstraint(['Idtemperature'], ['hy_dTemperatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_msg_fMessages',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ClientName', sa.String(length=255), nullable=True),
    sa.Column('IdClient', sa.Integer(), nullable=False),
    sa.Column('ClientNew', sa.Boolean(), nullable=False),
    sa.Column('CNA', sa.Boolean(), nullable=False),
    sa.Column('AssignmentDate', sa.DateTime(), nullable=True),
    sa.Column('Message', sa.Text(), nullable=True),
    sa.Column('Subject', sa.Text(), nullable=True),
    sa.Column('MessageDate', sa.DateTime(), nullable=True),
    sa.Column('IdBrokerResponsible', sa.Integer(), nullable=True),
    sa.Column('IdBrokerManager', sa.Integer(), nullable=True),
    sa.Column('IdProduct', sa.Integer(), nullable=True),
    sa.Column('IdChannel', sa.Integer(), nullable=True),
    sa.Column('IdSubChannel', sa.Integer(), nullable=True),
    sa.Column('IdMoment', sa.Integer(), nullable=True),
    sa.Column('IdSubMoment', sa.Integer(), nullable=True),
    sa.Column('IdMedia', sa.Integer(), nullable=True),
    sa.Column('IdMediaGroup', sa.Integer(), nullable=True),
    sa.Column('IdTemperature', sa.Integer(), nullable=True),
    sa.Column('IdStatusMessage', sa.Integer(), nullable=True),
    sa.Column('IdMessageType', sa.Integer(), nullable=True),
    sa.Column('IdResponsibleClient', sa.Integer(), nullable=True),
    sa.Column('IdResponsibleClientShared', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IdBrokerManager'], ['hy_msg_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdBrokerResponsible'], ['hy_msg_dUsers.id'], ),
    sa.ForeignKeyConstraint(['IdChannel'], ['hy_dChannels.id'], ),
    sa.ForeignKeyConstraint(['IdMedia'], ['hy_dMedias.id'], ),
    sa.ForeignKeyConstraint(['IdMediaGroup'], ['hy_dMediaGroups.id'], ),
    sa.ForeignKeyConstraint(['IdMessageType'], ['hy_msg_dType.id'], ),
    sa.ForeignKeyConstraint(['IdMoment'], ['hy_dMoments.id'], ),
    sa.ForeignKeyConstraint(['IdProduct'], ['hy_dProducts.id'], ),
    sa.ForeignKeyConstraint(['IdStatusMessage'], ['hy_msg_dStatus.id'], ),
    sa.ForeignKeyConstraint(['IdSubChannel'], ['hy_dSubChannels.id'], ),
    sa.ForeignKeyConstraint(['IdSubMoment'], ['hy_dSubMoments.id'], ),
    sa.ForeignKeyConstraint(['IdTemperature'], ['hy_dTemperatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_product_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CodProduto', sa.Integer(), nullable=True),
    sa.Column('Cep', sa.String(length=255), nullable=True),
    sa.Column('Logradouro', sa.String(length=255), nullable=True),
    sa.Column('Numero', sa.String(length=255), nullable=True),
    sa.Column('Complemento', sa.String(length=255), nullable=True),
    sa.Column('Estado', sa.String(length=255), nullable=True),
    sa.Column('Cidade', sa.String(length=255), nullable=True),
    sa.Column('Bairro', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['CodProduto'], ['hy_products.CodProduto'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_product_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CodProduto', sa.Integer(), nullable=True),
    sa.Column('idUnidade', sa.Integer(), nullable=False),
    sa.Column('TipoUnidade', sa.String(length=255), nullable=True),
    sa.Column('Finalidade', sa.String(length=255), nullable=True),
    sa.Column('Transacao', sa.String(length=255), nullable=True),
    sa.Column('Valor', sa.Float(), nullable=True),
    sa.Column('TotalComodos', sa.Integer(), nullable=True),
    sa.Column('TotalDormitorio', sa.Integer(), nullable=True),
    sa.Column('TotalAreaUtil', sa.Float(), nullable=True),
    sa.Column('TotalAreaTotal', sa.Float(), nullable=True),
    sa.Column('TotalSuite', sa.Integer(), nullable=True),
    sa.Column('TotalBanheiro', sa.Integer(), nullable=True),
    sa.Column('TotalVaga', sa.Integer(), nullable=True),
    sa.Column('TotalPeDireito', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['CodProduto'], ['hy_products.CodProduto'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dClientAdress',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('idState', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('idCity', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('idNeighborhood', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('ZipCode', sa.String(length=255), nullable=True),
    sa.Column('PublicPlace', sa.String(length=255), nullable=True),
    sa.Column('Number', sa.String(length=255), nullable=True),
    sa.Column('Complement', sa.String(length=255), nullable=True),
    sa.Column('Type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['hy_c_fClients.id'], ),
    sa.ForeignKeyConstraint(['idCity'], ['hy_c_dCity.id'], ),
    sa.ForeignKeyConstraint(['idNeighborhood'], ['hy_c_dNeighborhood.id'], ),
    sa.ForeignKeyConstraint(['idState'], ['hy_c_dState.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dClientEmails',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('EmailType', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['hy_c_fClients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dClientPhones',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Phone', sa.String(length=255), nullable=True),
    sa.Column('PhoneDDD', sa.String(length=255), nullable=True),
    sa.Column('PhoneType', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['hy_c_fClients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dDemographic',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('CpfValue', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('idGender', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('idMaritalStatus', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('ProductType', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('Phase', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('Finality', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('TimeSearch', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('TimeDecision', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('LiveInvest', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('PaymentPlan', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('MoreImportant', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('FGTSValue', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('EntryValue', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('MonthlyIncome', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('BirthDate', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('SpouseName', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('QtyDependents', sa.String(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['hy_c_fClients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dDescriptions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['hy_c_fClients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_c_dRanges',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('PriceFrom', sa.String(length=255), nullable=True),
    sa.Column('PriceTo', sa.String(length=255), nullable=True),
    sa.Column('AreaFrom', sa.String(length=255), nullable=True),
    sa.Column('AreaTo', sa.String(length=255), nullable=True),
    sa.Column('BedroomsFrom', sa.String(length=255), nullable=True),
    sa.Column('BedroomsTo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['hy_c_fClients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_ch_dConversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('Sender', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('UsersOnly', sa.Text(), nullable=True),
    sa.Column('User', sa.Text(), nullable=True),
    sa.Column('SubmissionDate', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_chat'], ['hy_ch_fChat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_msg_dEmail',
    sa.Column('IdClientMessage', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdClientMessage'], ['hy_msg_fMessages.id'], ),
    sa.PrimaryKeyConstraint('IdClientMessage')
    )
    op.create_table('hy_msg_dPhone',
    sa.Column('IdClientMessage', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('phone_ddd', sa.String(length=50), nullable=True),
    sa.Column('phone_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['IdClientMessage'], ['hy_msg_fMessages.id'], ),
    sa.PrimaryKeyConstraint('IdClientMessage')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hy_msg_dPhone')
    op.drop_table('hy_msg_dEmail')
    op.drop_table('hy_ch_dConversation')
    op.drop_table('hy_c_dRanges')
    op.drop_table('hy_c_dDescriptions')
    op.drop_table('hy_c_dDemographic')
    op.drop_table('hy_c_dClientPhones')
    op.drop_table('hy_c_dClientEmails')
    op.drop_table('hy_c_dClientAdress')
    op.drop_table('hy_product_units')
    op.drop_table('hy_product_addresses')
    op.drop_table('hy_msg_fMessages')
    op.drop_table('hy_ch_fChat')
    op.drop_table('hy_c_fClients')
    op.drop_table('job_logs')
    op.drop_table('hy_users')
    op.drop_table('hy_products')
    op.drop_table('hy_msg_dUsers')
    op.drop_table('hy_msg_dType')
    op.drop_table('hy_msg_dStatus')
    op.drop_table('hy_dTemperatures')
    op.drop_table('hy_dSubMoments')
    op.drop_table('hy_dSubChannels')
    op.drop_table('hy_dProducts')
    op.drop_table('hy_dMoments')
    op.drop_table('hy_dMedias')
    op.drop_table('hy_dMediaGroups')
    op.drop_table('hy_dChannels')
    op.drop_table('hy_ch_dUsers')
    op.drop_table('hy_ch_dRating')
    op.drop_table('hy_c_dUsers')
    op.drop_table('hy_c_dStatus')
    op.drop_table('hy_c_dState')
    op.drop_table('hy_c_dObjectives')
    op.drop_table('hy_c_dNeighborhood')
    op.drop_table('hy_c_dMaritalStatus')
    op.drop_table('hy_c_dInactiveStates')
    op.drop_table('hy_c_dGender')
    op.drop_table('hy_c_dFirstProperty')
    op.drop_table('hy_c_dCity')
    # ### end Alembic commands ###
