"""add model products

Revision ID: 1f524a6aa35b
Revises: 4023308b75b4
Create Date: 2024-05-27 21:10:49.488639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f524a6aa35b'
down_revision: Union[str, None] = '4023308b75b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hy_products',
    sa.Column('CodProduto', sa.Integer(), nullable=False),
    sa.Column('CodInterno', sa.Integer(), nullable=True),
    sa.Column('DataAtualizacao', sa.DateTime(), nullable=True),
    sa.Column('CodRegional', sa.Integer(), nullable=True),
    sa.Column('Produto', sa.String(length=255), nullable=False),
    sa.Column('Regional', sa.String(length=50), nullable=True),
    sa.Column('Finalidade', sa.String(length=50), nullable=True),
    sa.Column('IdTipoProduto', sa.Integer(), nullable=True),
    sa.Column('TipoProduto', sa.String(length=50), nullable=True),
    sa.Column('FaseProduto', sa.String(length=50), nullable=True),
    sa.Column('Descricao', sa.Text(), nullable=True),
    sa.Column('AnoEntrega', sa.Integer(), nullable=True),
    sa.Column('ValorDe', sa.Float(), nullable=True),
    sa.Column('ValorAte', sa.Float(), nullable=True),
    sa.Column('AreaUtilDe', sa.Float(), nullable=True),
    sa.Column('AreaUtilAte', sa.Float(), nullable=True),
    sa.Column('DormitoriosDe', sa.Integer(), nullable=True),
    sa.Column('DormitoriosAte', sa.Integer(), nullable=True),
    sa.Column('SuitesDe', sa.Integer(), nullable=True),
    sa.Column('SuitesAte', sa.Integer(), nullable=True),
    sa.Column('BanheiroDe', sa.Integer(), nullable=True),
    sa.Column('BanheiroAte', sa.Integer(), nullable=True),
    sa.Column('VagasDe', sa.Integer(), nullable=True),
    sa.Column('VagasAte', sa.Integer(), nullable=True),
    sa.Column('Caracteristicas', sa.Text(), nullable=True),
    sa.Column('UrlChat', sa.String(length=255), nullable=True),
    sa.Column('TotalBanheiroDe', sa.Integer(), nullable=True),
    sa.Column('TotalBanheiroAte', sa.Integer(), nullable=True),
    sa.Column('TotalVagaDe', sa.Integer(), nullable=True),
    sa.Column('TotalVagaAte', sa.Integer(), nullable=True),
    sa.Column('TotalDormitorioDe', sa.Integer(), nullable=True),
    sa.Column('TotalDormitorioAte', sa.Integer(), nullable=True),
    sa.Column('TotalAreaUtilDe', sa.Float(), nullable=True),
    sa.Column('TotalAreaUtilAte', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('CodProduto')
    )
    op.create_table('hy_product_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CodProduto', sa.Integer(), nullable=True),
    sa.Column('Cep', sa.String(length=255), nullable=False),
    sa.Column('Logradouro', sa.String(length=255), nullable=False),
    sa.Column('Numero', sa.String(length=255), nullable=False),
    sa.Column('Complemento', sa.String(length=255), nullable=False),
    sa.Column('Estado', sa.String(length=255), nullable=False),
    sa.Column('Cidade', sa.String(length=255), nullable=False),
    sa.Column('Bairro', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['CodProduto'], ['hy_products.CodProduto'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_product_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CodProduto', sa.Integer(), nullable=True),
    sa.Column('idUnidade', sa.Integer(), nullable=False),
    sa.Column('TipoUnidade', sa.String(length=255), nullable=False),
    sa.Column('Finalidade', sa.String(length=255), nullable=False),
    sa.Column('Transacao', sa.String(length=255), nullable=False),
    sa.Column('Valor', sa.Float(), nullable=True),
    sa.Column('TotalComodos', sa.Integer(), nullable=False),
    sa.Column('TotalDormitorio', sa.Integer(), nullable=False),
    sa.Column('TotalAreaUtil', sa.Float(), nullable=False),
    sa.Column('TotalAreaTotal', sa.Float(), nullable=False),
    sa.Column('TotalSuite', sa.Integer(), nullable=False),
    sa.Column('TotalBanheiro', sa.Integer(), nullable=False),
    sa.Column('TotalVaga', sa.Integer(), nullable=False),
    sa.Column('TotalPeDireito', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['CodProduto'], ['hy_products.CodProduto'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hy_product_units')
    op.drop_table('hy_product_addresses')
    op.drop_table('hy_products')
    # ### end Alembic commands ###
