"""Initial Commit

Revision ID: 4023308b75b4
Revises: 
Create Date: 2024-05-21 17:44:52.816668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4023308b75b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hy_clients',
    sa.Column('CodCliente', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(length=255), nullable=True),
    sa.Column('Cpf', sa.String(length=20), nullable=True),
    sa.Column('DataUltimaInteracao', sa.DateTime(), nullable=True),
    sa.Column('DataCadastro', sa.DateTime(), nullable=True),
    sa.Column('Momento', sa.String(length=50), nullable=True),
    sa.Column('Submomento', sa.String(length=50), nullable=True),
    sa.Column('Temperatura', sa.String(length=20), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('InactiveState', sa.String(length=50), nullable=True),
    sa.Column('InactiveStateId', sa.Integer(), nullable=True),
    sa.Column('Objetivo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('CodCliente')
    )
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('num_records', sa.Integer(), nullable=True),
    sa.Column('unique_emails', sa.Integer(), nullable=True),
    sa.Column('unique_phones', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('param_data_inicio', sa.String(length=50), nullable=False),
    sa.Column('param_data_atualizacao_inicio', sa.String(length=50), nullable=False),
    sa.Column('param_data_atualizacao_final', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_client_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['hy_clients.CodCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_client_demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('estadocivil', sa.String(length=50), nullable=True),
    sa.Column('NomeConjuge', sa.String(length=255), nullable=True),
    sa.Column('QtdDependentes', sa.Integer(), nullable=True),
    sa.Column('ValorFgts', sa.Float(), nullable=True),
    sa.Column('ValorEntrada', sa.Float(), nullable=True),
    sa.Column('ValorRendaMensal', sa.Float(), nullable=True),
    sa.Column('DataNascimento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['hy_clients.CodCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_client_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['hy_clients.CodCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_client_genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('Sexo', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['hy_clients.CodCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_client_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('ddd', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['hy_clients.CodCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_client_product_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('CodProduto', sa.String(length=50), nullable=True),
    sa.Column('CodInterno', sa.String(length=50), nullable=True),
    sa.Column('produto', sa.String(length=255), nullable=True),
    sa.Column('data_oferta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['hy_clients.CodCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_client_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('NomeCorretor', sa.String(length=255), nullable=True),
    sa.Column('EmailCorretor', sa.String(length=255), nullable=True),
    sa.Column('CpfCorretor', sa.String(length=255), nullable=True),
    sa.Column('NomeGerenteGeral', sa.String(length=255), nullable=True),
    sa.Column('EmailGerenteGeral', sa.String(length=255), nullable=True),
    sa.Column('NomeGerente', sa.String(length=255), nullable=True),
    sa.Column('EmailGerente', sa.String(length=255), nullable=True),
    sa.Column('NomeCoordenador', sa.String(length=255), nullable=True),
    sa.Column('EmailCoordenador', sa.String(length=255), nullable=True),
    sa.Column('NomeCorretorCompartilhado', sa.String(length=255), nullable=True),
    sa.Column('EmailCorretorCompartilhado', sa.String(length=255), nullable=True),
    sa.Column('RegionalCorretor', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['hy_clients.CodCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_client_trackings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('CanalOrigem', sa.String(length=50), nullable=True),
    sa.Column('MidiaOrigem', sa.String(length=255), nullable=True),
    sa.Column('MidiaAtual', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['hy_clients.CodCliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hy_client_trackings')
    op.drop_table('hy_client_teams')
    op.drop_table('hy_client_product_interests')
    op.drop_table('hy_client_phones')
    op.drop_table('hy_client_genders')
    op.drop_table('hy_client_emails')
    op.drop_table('hy_client_demographics')
    op.drop_table('hy_client_addresses')
    op.drop_table('job_logs')
    op.drop_table('hy_clients')
    # ### end Alembic commands ###
