"""messages_add_table

Revision ID: 5586f48e72a4
Revises: 9abfa39d8118
Create Date: 2024-06-13 21:12:01.206004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5586f48e72a4'
down_revision: Union[str, None] = '9abfa39d8118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hy_dim_canal',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('NomeCanal', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dim_grupo_midia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_midia', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dim_midia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('midia', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dim_momento',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('NomeMomento', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dim_sub_canal',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('NomeSubCanal', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dim_sub_momento',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('NomeSubMomento', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_dim_temperatura',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('NomeTemperatura', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_message_brooker',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('NomeCorretorResponsavel', sa.String(length=255), nullable=False),
    sa.Column('EmailCorretorResponsavel', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_message_dim_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StatusMensagem', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_message_dim_tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TipoMensagem', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_message_manager',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('NomeGerenteCorretorResponsavel', sa.String(length=255), nullable=False),
    sa.Column('EmailGerenteCorretorResponsavel', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_message',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('IDCliente', sa.Integer(), nullable=False),
    sa.Column('ClienteNovo', sa.Boolean(), nullable=False),
    sa.Column('CNA', sa.Boolean(), nullable=False),
    sa.Column('DataAtribuicao', sa.DateTime(), nullable=True),
    sa.Column('Mensagem', sa.Text(), nullable=True),
    sa.Column('Assunto', sa.Text(), nullable=True),
    sa.Column('Datamensagem', sa.DateTime(), nullable=True),
    sa.Column('IDCorretorResponsavel', sa.Integer(), nullable=True),
    sa.Column('IDGerenteCorretorResponsavel', sa.Integer(), nullable=True),
    sa.Column('IDProduto', sa.Integer(), nullable=True),
    sa.Column('IDCanal', sa.Integer(), nullable=True),
    sa.Column('IDSubCanal', sa.Integer(), nullable=True),
    sa.Column('IDMomento', sa.Integer(), nullable=True),
    sa.Column('IDSubMomento', sa.Integer(), nullable=True),
    sa.Column('IDMidia', sa.Integer(), nullable=True),
    sa.Column('IDGrupoMidia', sa.Integer(), nullable=True),
    sa.Column('IDTemperatura', sa.Integer(), nullable=True),
    sa.Column('IDMensageStatus', sa.Integer(), nullable=True),
    sa.Column('IDTipoMensagem', sa.Integer(), nullable=True),
    sa.Column('IDResponsavelCliente', sa.Integer(), nullable=True),
    sa.Column('IDResponsavelClienteCompartilhado', sa.Integer(), nullable=True),
    sa.Column('NomeCliente', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['IDCanal'], ['hy_dim_canal.id'], ),
    sa.ForeignKeyConstraint(['IDCorretorResponsavel'], ['hy_message_brooker.id'], ),
    sa.ForeignKeyConstraint(['IDGerenteCorretorResponsavel'], ['hy_message_manager.id'], ),
    sa.ForeignKeyConstraint(['IDGrupoMidia'], ['hy_dim_grupo_midia.id'], ),
    sa.ForeignKeyConstraint(['IDMensageStatus'], ['hy_message_dim_status.id'], ),
    sa.ForeignKeyConstraint(['IDMidia'], ['hy_dim_midia.id'], ),
    sa.ForeignKeyConstraint(['IDMomento'], ['hy_dim_momento.id'], ),
    sa.ForeignKeyConstraint(['IDProduto'], ['hy_products.CodProduto'], ),
    sa.ForeignKeyConstraint(['IDSubCanal'], ['hy_dim_sub_canal.id'], ),
    sa.ForeignKeyConstraint(['IDSubMomento'], ['hy_dim_sub_momento.id'], ),
    sa.ForeignKeyConstraint(['IDTemperatura'], ['hy_dim_temperatura.id'], ),
    sa.ForeignKeyConstraint(['IDTipoMensagem'], ['hy_message_dim_tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_message_email',
    sa.Column('IDMensagemCliente', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IDMensagemCliente'], ['hy_message.id'], ),
    sa.PrimaryKeyConstraint('IDMensagemCliente')
    )
    op.create_table('hy_message_tel',
    sa.Column('IDMensagemCliente', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(length=50), nullable=False),
    sa.Column('tel_ddd', sa.String(length=50), nullable=True),
    sa.Column('tel_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['IDMensagemCliente'], ['hy_message.id'], ),
    sa.PrimaryKeyConstraint('IDMensagemCliente')
    )

    # Alterar a tabela existente para remover AUTO_INCREMENT
    op.execute('ALTER TABLE hy_products MODIFY CodProduto INT NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hy_message_tel')
    op.drop_table('hy_message_email')
    op.drop_table('hy_message')
    op.drop_table('hy_message_manager')
    op.drop_table('hy_message_dim_tipo')
    op.drop_table('hy_message_dim_status')
    op.drop_table('hy_message_brooker')
    op.drop_table('hy_dim_temperatura')
    op.drop_table('hy_dim_sub_momento')
    op.drop_table('hy_dim_sub_canal')
    op.drop_table('hy_dim_momento')
    op.drop_table('hy_dim_midia')
    op.drop_table('hy_dim_grupo_midia')
    op.drop_table('hy_dim_canal')

    # Reverter a alteração, adicionando AUTO_INCREMENT de volta (se necessário)
    op.execute('ALTER TABLE hy_products MODIFY CodProduto INT NOT NULL AUTO_INCREMENT')
    # ### end Alembic commands ###
