"""alter nullable fields on job logs

Revision ID: 9abfa39d8118
Revises: 4f6274db1132
Create Date: 2024-05-28 07:54:08.646659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9abfa39d8118'
down_revision: Union[str, None] = '4f6274db1132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_logs', 'param_data_inicio',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('job_logs', 'param_data_atualizacao_inicio',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('job_logs', 'param_data_atualizacao_final',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('job_logs', 'endpoint',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_logs', 'endpoint',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('job_logs', 'param_data_atualizacao_final',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('job_logs', 'param_data_atualizacao_inicio',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('job_logs', 'param_data_inicio',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
