"""messages_add_table_fix_3

Revision ID: b4bc6f4242a7
Revises: f4a847eab19f
Create Date: 2024-06-15 23:06:21.655288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4bc6f4242a7'
down_revision: Union[str, None] = 'f4a847eab19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hy_chat', 'ActiveClient',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('hy_chat_rating', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hy_chat_rating', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('hy_chat', 'ActiveClient',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
