"""chat_create_table

Revision ID: de4cf2f3175e
Revises: 5586f48e72a4
Create Date: 2024-06-15 22:20:39.027551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de4cf2f3175e'
down_revision: Union[str, None] = '5586f48e72a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hy_chat_broker_attendant',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('AttendantBrokerName', sa.String(length=255), nullable=False),
    sa.Column('AttendantBrokerEmail', sa.String(length=255), nullable=False),
    sa.Column('AttendantBrokerPhoto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_chat_broker_forwarded',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ForwardedBrokerName', sa.String(length=255), nullable=False),
    sa.Column('ForwardedBrokerEmail', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_chat_broker_responsible',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ResponsibleBrokerName', sa.String(length=255), nullable=False),
    sa.Column('ResponsibleBrokerEmail', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_chat_manager_responsible',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ResponsibleManagerName', sa.String(length=255), nullable=False),
    sa.Column('ResponsibleManagerEmail', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_chat_rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('Rating', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_chat',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ClientName', sa.String(length=255), nullable=True),
    sa.Column('ClientEmail', sa.String(length=255), nullable=True),
    sa.Column('ClientPhone', sa.String(length=255), nullable=True),
    sa.Column('ClientIP', sa.String(length=50), nullable=True),
    sa.Column('ChatType', sa.Integer(), nullable=False),
    sa.Column('ActiveClient', sa.Boolean(), nullable=False),
    sa.Column('NewClient', sa.Boolean(), nullable=False),
    sa.Column('StartTimeDate', sa.DateTime(), nullable=True),
    sa.Column('EndTimeDate', sa.DateTime(), nullable=True),
    sa.Column('RatingComment', sa.Text(), nullable=True),
    sa.Column('IdBroker_responsible', sa.Integer(), nullable=True),
    sa.Column('IdBroker_attendant', sa.Integer(), nullable=True),
    sa.Column('IdBroker_forwarded', sa.Integer(), nullable=True),
    sa.Column('IdManager_responsible', sa.Integer(), nullable=True),
    sa.Column('IdRating', sa.Integer(), nullable=True),
    sa.Column('IdProduct', sa.Integer(), nullable=True),
    sa.Column('IdClient', sa.Integer(), nullable=True),
    sa.Column('IdChannel', sa.Integer(), nullable=True),
    sa.Column('IdSubChannel', sa.Integer(), nullable=True),
    sa.Column('IdMoment', sa.Integer(), nullable=True),
    sa.Column('IdSubMoment', sa.Integer(), nullable=True),
    sa.Column('IdMedium', sa.Integer(), nullable=True),
    sa.Column('IdMediumGroup', sa.Integer(), nullable=True),
    sa.Column('Idtemperature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IdBroker_attendant'], ['hy_chat_broker_attendant.id'], ),
    sa.ForeignKeyConstraint(['IdBroker_forwarded'], ['hy_chat_broker_forwarded.id'], ),
    sa.ForeignKeyConstraint(['IdBroker_responsible'], ['hy_chat_broker_responsible.id'], ),
    sa.ForeignKeyConstraint(['IdChannel'], ['hy_dim_canal.id'], ),
    sa.ForeignKeyConstraint(['IdClient'], ['hy_clients.CodCliente'], ),
    sa.ForeignKeyConstraint(['IdManager_responsible'], ['hy_chat_manager_responsible.id'], ),
    sa.ForeignKeyConstraint(['IdMedium'], ['hy_dim_midia.id'], ),
    sa.ForeignKeyConstraint(['IdMediumGroup'], ['hy_dim_grupo_midia.id'], ),
    sa.ForeignKeyConstraint(['IdMoment'], ['hy_dim_momento.id'], ),
    sa.ForeignKeyConstraint(['IdProduct'], ['hy_products.CodProduto'], ),
    sa.ForeignKeyConstraint(['IdRating'], ['hy_chat_rating.id'], ),
    sa.ForeignKeyConstraint(['IdSubChannel'], ['hy_dim_sub_canal.id'], ),
    sa.ForeignKeyConstraint(['IdSubMoment'], ['hy_dim_sub_momento.id'], ),
    sa.ForeignKeyConstraint(['Idtemperature'], ['hy_dim_temperatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hy_chat_conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('Sender', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('UsersOnly', sa.Text(), nullable=True),
    sa.Column('User', sa.Text(), nullable=True),
    sa.Column('SubmissionDate', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_chat'], ['hy_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('job_logs', 'error_message',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_logs', 'error_message',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_table('hy_chat_conversation')
    op.drop_table('hy_chat')
    op.drop_table('hy_chat_rating')
    op.drop_table('hy_chat_manager_responsible')
    op.drop_table('hy_chat_broker_responsible')
    op.drop_table('hy_chat_broker_forwarded')
    op.drop_table('hy_chat_broker_attendant')
    # ### end Alembic commands ###
