"""messages_add_users

Revision ID: e8f7f9e2e61f
Revises: b4bc6f4242a7
Create Date: 2024-06-22 23:58:31.594402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e8f7f9e2e61f'
down_revision: Union[str, None] = 'b4bc6f4242a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hy_users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Creci', sa.String(length=255), nullable=True),
    sa.Column('CreciType', sa.String(length=255), nullable=True),
    sa.Column('CreciValidity', sa.String(length=255), nullable=True),
    sa.Column('CPF', sa.String(length=255), nullable=True),
    sa.Column('IdProfile', sa.Integer(), nullable=True),
    sa.Column('IdManager', sa.Integer(), nullable=True),
    sa.Column('IdManager1', sa.Integer(), nullable=True),
    sa.Column('IdManager2', sa.Integer(), nullable=True),
    sa.Column('IdManager3', sa.Integer(), nullable=True),
    sa.Column('IdManager4', sa.Integer(), nullable=True),
    sa.Column('IdManager5', sa.Integer(), nullable=True),
    sa.Column('IdManager6', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('NickName', sa.String(length=255), nullable=True),
    sa.Column('Phone', sa.String(length=255), nullable=True),
    sa.Column('Photo', sa.String(length=255), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.Column('LegacyUserId', sa.Integer(), nullable=True),
    sa.Column('DescriptionStatus', sa.String(length=255), nullable=True),
    sa.Column('DateRegister', sa.DateTime(), nullable=True),
    sa.Column('DateUpdate', sa.DateTime(), nullable=True),
    sa.Column('DateBirth', sa.DateTime(), nullable=True),
    sa.Column('DateAdmission', sa.DateTime(), nullable=True),
    sa.Column('DateLastEvaluation', sa.DateTime(), nullable=True),
    sa.Column('Gender', sa.String(length=255), nullable=True),
    sa.Column('AverageRating', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('hy_chat_rating', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hy_chat_rating', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_table('hy_users')
    # ### end Alembic commands ###
