"""chat_create_table_fix

Revision ID: f4a847eab19f
Revises: de4cf2f3175e
Create Date: 2024-06-15 22:40:37.718526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f4a847eab19f'
down_revision: Union[str, None] = 'de4cf2f3175e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hy_chat_ibfk_5', 'hy_chat', type_='foreignkey')
    op.alter_column('hy_chat_rating', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hy_chat_rating', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.create_foreign_key('hy_chat_ibfk_5', 'hy_chat', 'hy_clients', ['IdClient'], ['CodCliente'])
    # ### end Alembic commands ###
